# Generated by Django 2.2.4 on 2019-08-09 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('damage', models.IntegerField()),
                ('picture', models.FileField(upload_to='static/pictures/ability')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('picture', models.FileField(upload_to='static/pictures/character/')),
                ('abilities', models.ManyToManyField(to='api.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='CosplayElement',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('victor', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('picture', models.FileField(upload_to='static/pictures/fight/')),
                ('team_evil', models.ManyToManyField(related_name='team_evil', to=settings.AUTH_USER_MODEL)),
                ('team_good', models.ManyToManyField(related_name='team_good', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('picture', models.FileField(upload_to='static/pictures/event/')),
                ('characters', models.ManyToManyField(to='api.Character')),
                ('fights', models.ManyToManyField(to='api.Fight')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('sub_events', models.ManyToManyField(to='api.SubEvent')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='cosplay_elements',
            field=models.ManyToManyField(to='api.CosplayElement'),
        ),
    ]
