# Generated by Django 2.2.4 on 2019-08-09 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendedCharacter',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Character')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
